services:
  db:
    image: postgres:15
    container_name: coupon_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coupons
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: coupon_backend
    ports:
      - "3000:3000"
      - "5555:5555"
      
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/coupons"
    volumes:
      - ./backend:/app

volumes:
  postgres_data:




